// <auto-generated />
namespace RestaurantsData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class enum51 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enum51));
        
        string IMigrationMetadata.Id
        {
            get { return "202106160624568_enum51"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
